### ISSUE TITLE
переделать на rx-оператор map

### ISSUE THREAD

**Issue by tamazyanarsen** [IvanMax1996/todolist#10]
https://github.com/IvanMax1996/todolist/blob/8f7dabeace1bb8d388bce51c17125c0fcdfa6c5e/src/app/shared/services/todolist.service.ts#L14

**Comment by IvanMax1996** [comment]
> https://github.com/IvanMax1996/todolist/blob/8f7dabeace1bb8d388bce51c17125c0fcdfa6c5e/src/app/shared/services/todolist.service.ts#L14

готово. переписал на оператор "map", заменив оператор "every" на функцию высшего порядка "every"
