### ISSUE TITLE
переделать на map

### ISSUE THREAD

**Issue by tamazyanarsen** [IvanMax1996/todolist#11]
https://github.com/IvanMax1996/todolist/blob/8f7dabeace1bb8d388bce51c17125c0fcdfa6c5e/src/app/shared/services/todolist.service.ts#L46

**Comment by IvanMax1996** [comment]
> https://github.com/IvanMax1996/todolist/blob/8f7dabeace1bb8d388bce51c17125c0fcdfa6c5e/src/app/shared/services/todolist.service.ts#L46

готово. переписал на оператор "map", заменив оператор "filter" на функцию высшего порядка "filter"
