### ISSUE TITLE
find

### ISSUE THREAD

**Issue by tamazyanarsen** [IvanMax1996/todolist#14]
https://github.com/IvanMax1996/todolist/blob/c83494ae9dc72e39fef4d439e12f3edd3bde4069/src/app/shared/services/todolist.service.ts#L54C41-L54C48

**Comment by IvanMax1996** [comment]
> https://github.com/IvanMax1996/todolist/blob/c83494ae9dc72e39fef4d439e12f3edd3bde4069/src/app/shared/services/todolist.service.ts#L54C41-L54C48

переписал на "find" с последующим поиском элемента по индексу
