### ISSUE TITLE
переделать на subject

### ISSUE THREAD

**Issue by tamazyanarsen** [IvanMax1996/todolist#8]
https://github.com/IvanMax1996/todolist/blob/f39d93e82d63222be7a03f334a56d41bac445506/src/app/shared/services/todolist.service.ts#L10

**Comment by IvanMax1996** [comment]
> https://github.com/IvanMax1996/todolist/blob/f39d93e82d63222be7a03f334a56d41bac445506/src/app/shared/services/todolist.service.ts#L10

приложение было переписано на "BehaviorSubject"
