### ISSUE TITLE
лишняя проверка

### ISSUE THREAD

**Issue by tamazyanarsen** [IvanMax1996/todolist#9]
https://github.com/IvanMax1996/todolist/blob/8f7dabeace1bb8d388bce51c17125c0fcdfa6c5e/src/app/shared/services/todolist.service.ts#L16

если там boolean, то зачем добавлять проверку?)

**Comment by IvanMax1996** [comment]
> https://github.com/IvanMax1996/todolist/blob/8f7dabeace1bb8d388bce51c17125c0fcdfa6c5e/src/app/shared/services/todolist.service.ts#L16
> 
> если там boolean, то зачем добавлять проверку?)

исправил. сократил проверку
